/*
 * WARNING: this file has been generated by
 * Hime Parser Generator 3.5.0.0
 */
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.IO;
using Hime.Redist;
using Hime.Redist.Lexer;

namespace SixCc.Hime
{
	/// <summary>
	/// Represents a lexer
	/// </summary>
	[GeneratedCodeAttribute("Hime.SDK", "3.5.0.0")]
	public class LinguLexer : ContextFreeLexer
	{
		/// <summary>
		/// The automaton for this lexer
		/// </summary>
		private static readonly Automaton commonAutomaton = Automaton.Find(typeof(LinguLexer), "LinguLexer.bin");
		/// <summary>
		/// Contains the constant IDs for the terminals for this lexer
		/// </summary>
		[GeneratedCodeAttribute("Hime.SDK", "3.5.0.0")]
		public class ID
		{
			/// <summary>
			/// The unique identifier for terminal BLOCK_COMMENT
			/// </summary>
			public const int TerminalBlockComment = 0x0007;
			/// <summary>
			/// The unique identifier for terminal SPACE
			/// </summary>
			public const int TerminalSpace = 0x0008;
			/// <summary>
			/// The unique identifier for terminal NAME
			/// </summary>
			public const int TerminalName = 0x000E;
			/// <summary>
			/// The unique identifier for terminal INTEGER
			/// </summary>
			public const int TerminalInteger = 0x000F;
			/// <summary>
			/// The unique identifier for terminal LITERAL_ANY
			/// </summary>
			public const int TerminalLiteralAny = 0x0011;
			/// <summary>
			/// The unique identifier for terminal LITERAL_TEXT
			/// </summary>
			public const int TerminalLiteralText = 0x0012;
			/// <summary>
			/// The unique identifier for terminal UNICODE_BLOCK
			/// </summary>
			public const int TerminalUnicodeBlock = 0x0013;
			/// <summary>
			/// The unique identifier for terminal UNICODE_CATEGORY
			/// </summary>
			public const int TerminalUnicodeCategory = 0x0014;
			/// <summary>
			/// The unique identifier for terminal UNICODE_CODEPOINT
			/// </summary>
			public const int TerminalUnicodeCodepoint = 0x0015;
		}
		/// <summary>
		/// Contains the constant IDs for the contexts for this lexer
		/// </summary>
		[GeneratedCodeAttribute("Hime.SDK", "3.5.0.0")]
		public class Context
		{
			/// <summary>
			/// The unique identifier for the default context
			/// </summary>
			public const int Default = 0;
		}
		/// <summary>
		/// The collection of terminals matched by this lexer
		/// </summary>
		/// <remarks>
		/// The terminals are in an order consistent with the automaton,
		/// so that terminal indices in the automaton can be used to retrieve the terminals in this table
		/// </remarks>
		private static readonly Symbol[] terminals = {
			new Symbol(0x0001, "ε"),
			new Symbol(0x0002, "$"),
			new Symbol(0x0007, "BLOCK_COMMENT"),
			new Symbol(0x0008, "SPACE"),
			new Symbol(0x000E, "NAME"),
			new Symbol(0x000F, "INTEGER"),
			new Symbol(0x0011, "LITERAL_ANY"),
			new Symbol(0x0012, "LITERAL_TEXT"),
			new Symbol(0x0013, "UNICODE_BLOCK"),
			new Symbol(0x0014, "UNICODE_CATEGORY"),
			new Symbol(0x0015, "UNICODE_CODEPOINT"),
			new Symbol(0x0029, "grammar"),
			new Symbol(0x002A, "{"),
			new Symbol(0x002D, "}"),
			new Symbol(0x002E, "options"),
			new Symbol(0x0031, "="),
			new Symbol(0x0032, ";"),
			new Symbol(0x0033, ".."),
			new Symbol(0x0034, "rules"),
			new Symbol(0x0037, ":"),
			new Symbol(0x0038, "->"),
			new Symbol(0x0039, "|"),
			new Symbol(0x003B, "-"),
			new Symbol(0x003D, "?"),
			new Symbol(0x003E, "*"),
			new Symbol(0x003F, "+"),
			new Symbol(0x0040, "("),
			new Symbol(0x0041, ")"),
			new Symbol(0x0042, "~") };
		/// <summary>
		/// Initializes a new instance of the lexer
		/// </summary>
		/// <param name="input">The lexer's input</param>
		public LinguLexer(string input) : base(commonAutomaton, terminals, 0x0008, input) {}
		/// <summary>
		/// Initializes a new instance of the lexer
		/// </summary>
		/// <param name="input">The lexer's input</param>
		public LinguLexer(TextReader input) : base(commonAutomaton, terminals, 0x0008, input) {}
	}
}
